### ISSUE TITLE
Aliased dependencies cannot be checked

### ISSUE THREAD

**Issue by timvisee** [kbknapp/cargo-outdated#167]
When having an aliased crate dependency, `cargo-outdated` fails to check for outdated crates returning an error.

In [`ffsend`](https://github.com/timvisee/ffsend) I've a crate dependency for `clipboard` aliassed to `clip`:
https://github.com/timvisee/ffsend/blob/d4efd984eb1c5a07d36bcba82b34d2c378db5dc0/Cargo.toml#L128

When running `cargo outdated -d1` it fails with the following error:
```
error: Direct dependency clip not found for package ffsend
```

This _might_ be related to the [`[target.'cfg(...)'.dependencies]`](https://github.com/timvisee/ffsend/blob/d4efd984eb1c5a07d36bcba82b34d2c378db5dc0/Cargo.toml#L126) header, but I believe it's just the alias causing this issue.

**Comment by azriel91** [comment]
Can confirm it's just the alias. With this:

https://github.com/alexheretic/glyph-brush/blob/glyph-brush-0.5/glyph-brush/Cargo.toml#L16

`cargo outdated` prints:

```bash
error: no matching package named `full_rusttype` found (required by `glyph_brush`)
location searched: registry `https://github.com/rust-lang/crates.io-index`
version required: ^0.7.5
```

That's actually an error in `cargo` ([relevant lines](https://github.com/rust-lang/cargo/blob/1ae512da978647df80494a7ac663961ccab61878/src/cargo/core/resolver/errors.rs#L265-L270))

**Comment by azriel91** [comment]
This is fixed by [updating to `cargo`'s `master` branch](https://github.com/azriel91/cargo-outdated/tree/use-cargo-master), so the bug is somewhere in Cargo. They haven't pushed a release though, so `cargo-outdated` can't simply depend on something from crates.io.

You can test it out using:

```bash
cargo install --git https://github.com/azriel91/cargo-outdated.git --branch use-cargo-master --force
```

**Comment by timvisee** [comment]
That's brilliant. Lets hope the changes on master are published soon.

Thank you for taking the effort to figure this out.

**Comment by bbigras** [comment]
Any progress on this?

**Comment by azriel91** [comment]
Built `cargo-outdated` from the `master` branch (which has already picked up the fix from `cargo`), and it successfully processes the `glyph-brush` crate.

**Comment by timvisee** [comment]
@azriel91 It still fails to handle the `Cargo.toml` in the [`ffsend`](https://github.com/timvisee/ffsend) repository using the latest `cargo-outdated` from master.

```bash
$ cargo outdated --version
cargo-outdated v0.9.0

$ git clone git@github.com:timvisee/ffsend.git
$ cd ffsend

$ cargo outdated
error: failed to parse manifest at `/tmp/cargo-outdatedJgP4X4/Cargo.toml`

Caused by:
  Features and dependencies cannot have the same name: `clipboard`
```

**Comment by Nemo157** [comment]
Minimal repro for the issue with reusing a dependencies true name as a feature name:

```console
> cargo new --lib foo && cd foo
     Created library `foo` package
> cat >> Cargo.toml <<END
c = { version = "*", package = "libc", optional = true }
[features]
libc = ["c"]
END
> cargo outdated -R
error: failed to parse manifest at `/var/folders/0p/5yvmrvhj5w3_vy1y8x7dvk7m0000gn/T/cargo-outdated3nElPk/Cargo.toml`

Caused by:
  Features and dependencies cannot have the same name: `libc`
> cargo build --features libc
   Compiling libc v0.2.62
   Compiling foo v0.1.0 (/private/var/folders/0p/5yvmrvhj5w3_vy1y8x7dvk7m0000gn/T/tmp.wZtlVGly/foo)
    Finished dev [unoptimized + debuginfo] target(s) in 2.41s
```
